// add navbar [done]
// add footer [done]
// add gallery [todo]
// add blog [done]
// add about [done]
// add authentication--- firebase [done till now]
// add forget password [todo]
// add axiosSecure using axios interceptors [todo]
// add authorization--- jwt [todo]
// add jwt Verification [done]
// user added to database [done]
// checking google user already added or not and based on that added to database or not [done]
// make item list or panel dynamic [todo:future]
// add booking section [todo]
// send request to add self picture to public section -- item post [todo]
// send request to update self picture from public section -- item update [todo]
// send request to delete self picture from public section -- item delete [todo]
// user dashboard -- profile, payment, request to shared blogs, likes blogs, commented blogs [todo]
// admin dashboard --permits to post user's blog, delete user blog from items, make admin, delete user  [todo]
// add helmet for dynamic title
// add animation to all pages [todo]
