// add navbar [done]
// add footer [done]
// add gallery [todo]
// add blog [done]
// add about [done]
// add axiosSecure using axios interceptors [done]
// add authorization--- jwt [done]
// add jwt Verification [done]
// user added to database [done]
// checking google user already added or not and based on that added to database or not [done]
// add session [done]
// add user booking on session [done]
// add adminRoute in frontend [done]
// add verifyAdmin in backend [done]
// add calender/date before booking item [done]
//
// make item list or panel dynamic [todo:future]
// add booking section [done]
// add user booking on session delete and send a delete message [done]
// add payment method, get all payment and get payment history [done]
// add get payment history for user[done]
// add and update item [done] ---- check
// user dashboard -- profile, payment, request to shared blogs, likes blogs, commented blogs [todo]
// admin dashboard --permits to post user's blog, delete user blog from items, make admin, delete user  [todo]
// add helmet for dynamic title [todo]
// add authentication--- firebase [done till now]
// add forget password [todo]
// add animation to all pages [todo]
